# global.R for session
message("Loading libraries for global environment")
library(shiny)
library(data.table)
library(lubridate)
library(ggplot2)
library(reshape)
library(knitr)
library(RCurl)
library(xtable)
